services:
  - type: web
    name: flora-client
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.17.0

  - type: web
    name: flora-api
    env: node
    rootDir: api
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
